name: Check Kubernetes documentation links (Scheduled)

on:
  schedule:
    - cron:  '* * */15 * *'

jobs:
  kubernetes-doc-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
